apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    log_type: {{ .Values.log_type }}
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: project/name
                operator: In
                values:
                  - roboshop
  topologySpreadConstraints:
    - topologyKey: kubernetes.io/hostname
      maxSkew: 1
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: {{ .Values.appName }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  replicas: {{ .Values.minReplicas }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          {{- if eq .Values.appName "frontend" }}
          image:  public.ecr.aws/w8x4g9h7/roboshop-v3/frontend
          {{- else }}
          image: azuredevopsb84.azurecr.io/roboshop-{{ .Values.appName }}:{{ .Values.appTag }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.port }}
          envFrom:
           - secretRef:
              name: {{ .Values.appName }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            failureThreshold: 1
            periodSeconds: 10
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.port }}
            failureThreshold: 1
            periodSeconds: 10
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}