apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.appName }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: {{ .Values.appName }}-job
  dataFrom:
    - extract:
        key: {{ .Values.appName }}-job